language: java
notifications:
  hipchat:
    rooms:
      secure: oEJ+AZVMxuhGqAWiv/mII6P3iG13tOjS18zfb5ywNNbuNfm+8oT3OO9LOVqOxb1pqYP8f3WZZgWYV1dDOG5S97z9z7BPU9k4QYCjZSRlUQ+ZXNhehfpiSrls9N4ZhPdY+ulFThU7MUHdkWx54AnU1K6qqmOcHVYMSqKk7vn22n9eqb02VqydxmmR7OVgnn2pANNe9++tFuZZzRgkJ4olNJa2I9o30Xh0+BjdIPZijIee98rN24SuY+T9eyJzsUEIDA5TgfIkGw5SilGA0pL9xSMmJR62w6IGsDtRRtLCoXKp1fseq6wdDBUlnnHN3AmW2bHOFuQ75cfGmUkcyb4itaPYmcVcTRAW4hJMb6F9bGT4XKy3tZWJmFUkQCuNKl0pwVNg/aJsHuBzITm7xztX/c18SN2WK49zWAi//dT8zDnaG4L1hKvKlRmH+cMr1CujD6mBIFfOFiK8ePU6TUS5LoGjIApxmejpdflfvzu5Pa1byaKPxgdm3BQY68AQegQk3h1K7oVH23UB3U1TS9fBjKkC4Y0sUSiZzo4KDin1+vnadw+D4bKpc9vw9h3iGYLy+jois7WOq5qxfW/ohzDkwgjd87GgcH4WSBLWAPodsZp6HwemsJOZq6t8H/aLjkaPv07OsguQ9xM3u2obMucXrIYnAusENw0HNEUo8bZOy0M=
deploy:
  provider: releases
  api_key:
    secure: pF3lUejaLDz4tq7ABeU+vZDpOnqbO59tdksHXCOzHAveMDzwmdojb9KdLGPG/z27PV/dNDELHux1Zxpd0fS28C7M4lkikiwO7DZfRMLlidqHN2QcGae1c8oEnx60MuwsxW4iUrblV4XijAyHpldRhDobV2lG4xY7yjxF/TKwww9W+JxZvc8WjwFTfsGKOA+TvVqILl/hhVhn+5tPke0yYXv1hQQwTeG7soCL0dppfEaIJFZ4PvZE/grh6mnxBPWKXm/iXw56athoRx5+qBMXL+8/x8TRc2HM/9xdr/GGlYsoKqBYmp4hVdEXx+uqGfZgx7xl+WhsHehIEW7E39Y8IyLJfucgSfSkhFR1uEjJbcxqAnwE3u2LQvw+2a1IkxPsADBIsPPAT4oXYbrwaoSmDYEGSv7gTWyUnT4rFF5PvGXhfMtdN5vuaz87hAO1G7h+3+JDeTqfIpQ5eHBRe/H+fbMYq9OaqTEiQDHvJRR/edfOYnL0lswZ8vhKgk/S8aejvXyG48DWr3AtrcyKEwJouNbIovfObbXlv+OsWC0+29vCvHj2F9oEtl2oFyBIMpVGEDgAL/gxJ8FngiVspVcFdc1UgZ9k54uxRlPddQmws/TWLQJhyZbOEQv8AvOrojXoXjuwvCblmK/Qw3nU48FuoXO4j0rW+aNVh/90hRmmzok=
  file: build/libs/xlr-jenkins2-plugin-1.1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-jenkins2-plugin
